### ISSUE TITLE
数式環境下での改行について

### ISSUE THREAD

**Issue by HirokiS25** [kumasaburou/num2019#17]
aligned環境でうまくいくと思います。
例：
$$
\begin{aligned}
nagai & shiki \\
&meccha nagai shiki
\end{aligned}
$$

**Comment by biyori-sh** [comment]
Github上でJupyterNotebookを見るとき、複数列の数式を$$ $$内のalign環境で表わすと改行で表示がおかしくなりましたが、$$ $$内のaligned環境で表わせば助言通り上手くいきました。
